safe: true
lsi: false
pygments: true
source: .
permalink: /:title/
baseurl: "/"
url: https://help.imamopravoznati.org
name: PomoÄ‡ za pristup informacijama
exclude:
- ".*"
- "*.md"
- "Gemfile*"
- "CNAME"

owner:
  name: Code for Croatia
  contact: "&#109;&#097;&#105;&#108;&#116;&#111;:&#104;&#105;&#064;&#099;&#111;&#100;&#101;&#102;&#111;&#114;&#099;&#114;&#111;&#097;&#116;&#105;&#097;&#046;&#111;&#114;&#103;"
  website: http://codeforcroatia.org
  github: https://github.com/codeforcroatia
  facebook: https://www.facebook.com/kodirajzahrvatsku
  
project:
  name: Imamo pravo znati
  githubslug: help-imamopravoznati
  website: http://imamopravoznati.org

license:
  name: CC0
  url: https://creativecommons.org/publicdomain/zero/1.0/deed.hr

analytics:
  provider: google
  google:
    id: UA-46708458-9
